import { NativeChapter } from '../../types/content';
export const chapter9: NativeChapter = {
  id: 'nlp', number: 'IX', title: 'Natural Language Processing',
  pages: [
    {
      pageNumber: 1,
      blocks: [
        { type: 'h1', content: '6.1 Introduction to NLP' },
        { type: 'h2', content: 'Natural Language Processing' },
        { type: 'p', content: 'Sub-field of Artificial Intelligence (AI). Enable computers to analyze, understand & process human language. Derive meaningful information from human communication.' },
        { type: 'h3', content: 'Applications' },
        { type: 'ul', items: [
          'Voice Assistants (Siri, Alexa)',
          'Autogenerated Captions (YouTube)',
          'Language Translations',
          'Sentiment Analysis',
          'Text Classification',
          'Keyword Extraction'
        ]}
      ]
    },
    {
      pageNumber: 2,
      blocks: [
        { type: 'h1', content: '6.3 Stages of NLP' },
        { type: 'ol', items: [
          'Lexical Analysis: Breaks large text -> paragraphs -> sentences -> words. Uses lexicon.',
          'Syntactic Analysis / Parsing: Checks grammar of sentences/phrases & eliminated logically incorrect sentence.',
          'Semantic Analysis: Focuses on meaning of words and phrases. (E.g. Hot ice cream is rejected).',
          'Discourse Integration: Establishing sentence relation with preceding + succeeding sentences.',
          'Pragmatic Analysis: Checks real world relevance. Discard the actual word meaning & take the intended meaning.'
        ]}
      ]
    },
    {
      pageNumber: 3,
      blocks: [
        { type: 'h1', content: '6.4 Chatbot & 6.5 Text Processing' },
        { type: 'h2', content: 'Chatbot' },
        { type: 'p', content: 'A computer program designed to simulate human conversation (voice/text). E.g. Script bot (rule-based) vs Smart bot (AI-driven).' },
        { type: 'h2', content: 'Text Processing' },
        { type: 'ol', items: [
          'Sentence Segmentation: Divide text into sentences.',
          'Tokenization: Sentences into words, numbers, characters.',
          'Removing Stop Words: the, is, and, are, etc. are removed.',
          'Converting Text to Common Case.',
          'Stemming: Reduce words to root form (healed -> heal).',
          'Lemmatization: Ensures meaningful base word (lemma).'
        ]}
      ]
    },
    {
      pageNumber: 4,
      blocks: [
        { type: 'h1', content: 'Bag of Words & TF-IDF' },
        { type: 'h2', content: 'Bag of words algorithm' },
        { type: 'p', content: 'Converts text into numbers by creating a vocabulary (unique words) and a frequency table.' },
        { type: 'h2', content: 'TF-IDF' },
        { type: 'p', content: 'Term Frequency Inverse Document Frequency. Improves BoW by weighing words based on importance.' },
        { type: 'ul', items: [
          'Term frequency (TF): How often a word appears in a document.',
          'Document frequency (DF): In how many documents a word appears.',
          'Inverse Document frequency (IDF): If a word appears in all docs, it\'s not special = low IDF.'
        ]}
      ]
    },
    {
      pageNumber: 5,
      blocks: [
        { type: 'h1', content: '6.6 NLP Tools & Usecases' },
        { type: 'h2', content: 'Code Based NLP Tools' },
        { type: 'ul', items: [
          'NLTK (Natural Language Toolkit): Python package for text processing.',
          'SpaCy: Open-source NLP library. Optimized for performance in real-world NLP applications.'
        ]},
        { type: 'h2', content: 'No Code Based NLP Tools' },
        { type: 'ul', items: [
          'Orange Data Mining: ML + Data analysis tool (Python + visual programming).',
          'MonkeyLearn: Text analysis platform with pre-trained + custom ML models.'
        ]}
      ]
    }
  ]
};
