import { NativeChapter } from '../../types/content';
export const chapter_nlp: NativeChapter = {
  id: 'nlp-custom', number: 'IV', title: 'Natural Language Processing',
  pages: [
    {
      pageNumber: 1,
      blocks: [
        { type: 'h1', content: 'Session 1: Introduction' },
        { type: 'h2', content: 'Natural Language?' },
        { type: 'ul', items: [
          'Human Languages: English, Hindi, Russian, Bhojpuri etc.',
          'Computer Languages: They can\'t understand human language. To interact with computer - Python, C++'
        ]},
        { type: 'definition', term: 'Natural Language Processing?', definition: 'Sub-field of Artificial Intelligence (AI). Enable computers to analyze, understand & process human language. Derive meaningful information from human communication. NLP: bridge between humans & machines.' },
        { type: 'p', content: 'NLP converts natural language into digital form, that computer understands' },
        { type: 'h1', content: 'Session 2: Applications' },
        { type: 'h2', content: 'Applications?' },
        { type: 'ul', items: [
          'Voice Assistants: Siri, Alexa',
          'Autogenerated Captions: YT',
          'Language Translations',
          'Sentiment Analysis',
          'Text Classification',
          'Keyword Extraction'
        ]}
      ]
    },
    {
      pageNumber: 2,
      blocks: [
        { type: 'h1', content: 'Session 3: Stages of NLP' },
        { type: 'h3', content: '1. Lexical Analysis' },
        { type: 'ul', items: [
          'Breaks large text -> paragraphs -> sentences -> words.',
          'Uses lexicon: collection of words, phrases'
        ]},
        { type: 'h3', content: '2. Syntactic Analysis / Parsing' },
        { type: 'ul', items: [
          'Checks grammar of sentences/phrases & eliminated logically incorrect sentence.'
        ]},
        { type: 'h3', content: '3. Semantic Analysis' },
        { type: 'ul', items: [
          'Focuses on meaning of words and phrases.',
          'Eg Hot ice cream (Syntactically correct but Semantically wrong)'
        ]},
        { type: 'h3', content: '4. Discourse Integration' },
        { type: 'ul', items: [
          'Forming story of the sentence.',
          'Establishing sentence relation with preceding + succeeding sentences.'
        ]},
        { type: 'h3', content: '5. Pragmatic Analysis' },
        { type: 'ul', items: [
          'Checks real world relevance, Pragmatic: Practical or logical',
          'Discard the actual word meaning & take the intended meaning',
          'Example: "Relax! I\'m just pulling your leg" Means he is just joking.'
        ]}
      ]
    },
    {
      pageNumber: 3,
      blocks: [
        { type: 'h1', content: 'Session 4 & 5: Chatbots & Text Processing' },
        { type: 'h2', content: 'Session 4: Chatbot' },
        { type: 'ul', items: [
          'A computer program designed to simulate human conversation (voice/text).',
          'Learns over time to interact better.',
          'Common uses: Answering FAQs & troubleshooting, Customer support',
          'Eg: Elizabot, Cleverbot'
        ]},
        { type: 'table', headers: ['Script bot', 'Smart bot'], rows: [
          ['Script bots are easy to make.', 'Smart-bots are flexible and powerful.'],
          ['Script bots work around a script which is programmed in them.', 'Smart bots work on bigger databases and other resources directly.'],
          ['Mostly they are free and are easy to integrate to a messaging platform.', 'Smart bots learn with more data.'],
          ['No or little language processing skills.', 'Coding is required to take this up on board.'],
          ['Limited functionality.', 'Wide functionality.']
        ]},
        { type: 'h2', content: 'Session 5: Text Processing' },
        { type: 'p', content: 'Goal: Convert human language into numerical format' },
        { type: 'h3', content: 'Text Normalisation?' },
        { type: 'ol', items: [
          'Sentence Segmentation: Divide (all text data) into sentences.',
          'Tokenization: Sentences into words, numbers, characters.',
          'Removing Stop Words, Special Chars & Nos: the, is, and, are, etc. are removed',
          'Converting Text to Common Case',
          'Stemming: Reduce words to root form, healed → heal, studies → studi (may be meaningless)',
          'Lemmatization: Ensures meaningful base word (lemma), Example: studies → study.'
        ]}
      ]
    },
    {
      pageNumber: 4,
      blocks: [
        { type: 'h1', content: 'Algorithms & Usecases' },
        { type: 'h2', content: 'Bag of words algorithm -' },
        { type: 'p', content: 'Converts text into numbers. Output - A vocabulary (unique words in the corpus). A frequency table (how many times each word appears in each document).' },
        { type: 'h2', content: 'TF-IDF' },
        { type: 'p', content: 'Term Frequency Inverse Document Frequency ? Improves BoW by weighing words based on importance.' },
        { type: 'ul', items: [
          'Term frequency (TF): How often a word appears in a document.',
          'Document frequency (DF): In how many documents a word appears.',
          'Inverse Document frequency (IDF): Formula: IDF = log(Total docs / DF). Idea: If a word appears in all docs, it\'s not special = low IDF. If a word appears in few docs = high IDF (more valuable).',
          'TF-IDF Score: Formula: TF * IDF. High score = important word for that document.'
        ]},
        { type: 'h1', content: 'Session 6: Usecase Walkthrough' },
        { type: 'h3', content: 'CODE BASED NLP TOOLS' },
        { type: 'ul', items: [
          '1. NLTK (Natural Language Toolkit): Python package for text processing. Provides modules for tokenization, stemming, parsing, classification, etc.',
          '2. SpaCy: Open-source NLP library. Features: tokenization, Parts of speech tagging, Named Entity Recognition, dependency parsing. Optimized for performance in real-world NLP applications.'
        ]},
        { type: 'h3', content: 'NO CODE BASED NLP TOOLS' },
        { type: 'ul', items: [
          '1. Orange Data Mining: ML + Data analysis tool (Python + visual programming). Drag-and-drop operations. Supports text mining, classification, clustering.',
          '2. MonkeyLearn: Text analysis platform with pre-trained + custom ML models. Tasks: classification, sentiment analysis, entity recognition.'
        ]},
        { type: 'h3', content: 'Sentiment Analysis' },
        { type: 'p', content: 'NLP technique to analyze if textual data = positive, negative, or neutral. Voice of the Customer (VoC): Analyzes customer feedback for insights.' }
      ]
    }
  ]
};
